[build]
  publish = "public"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://unpkg.com  https://cdnjs.cloudflare.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdnjs.cloudflare.com;
    font-src 'self' https://fonts.gstatic.com;
    img-src 'self' data: blob: https://*.tile.openstreetmap.org https://unpkg.com https://cdnjs.cloudflare.com;
    object-src 'none';
    base-uri 'self';
    form-action 'none';
  """

[[redirects]]
  from = "/images"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*.txt"
  to = "/"
  status = 403

[[redirects]]
  from = "/*.json"
  to = "/"
  status = 403

[[redirects]]
  from = "/*.js"
  to = "/"
  status = 403